/**
 * Type definitions for the AI-driven training system ("Palestra Mentale").
 *
 * Architecture: Worker stateless + frontend stateful.
 * Each Worker request carries the full conversation history.
 * All persistent state lives in encrypted localStorage (same PIN/PBKDF2/AES-256-GCM).
 *
 * Data model:
 * - TrainingSession: active session with conversation turns + scores
 * - BehaviorScores: per-turn emotional/cognitive analysis from Gemini
 * - ScenarioConfig: scenario parameters sent to Worker with each request
 * - ReflectionAnswer: user's answer to a guided reflection question
 * - UserProfile: cross-session vulnerability profile (V2)
 */

import type { AttackType } from './emergency';

// ---------------------------------------------------------------------------
// Vulnerability dimensions (4 axes from the document)
// ---------------------------------------------------------------------------

/** The 4 measurable dimensions of cognitive vulnerability */
export type TrainingDimension =
  | 'activation'    // emotional activation (urgency, fear, desire)
  | 'impulsivity'   // acting without thinking
  | 'verification'  // tendency to verify claims (POSITIVE — higher = safer)
  | 'awareness';    // recognizing manipulation patterns (POSITIVE — higher = safer)

// ---------------------------------------------------------------------------
// Behavior scores — returned by Gemini per user message
// ---------------------------------------------------------------------------

/** AI-computed behavioral scores for a single user message */
export interface BehaviorScores {
  /** Emotional activation level (0-100, higher = more activated) */
  readonly activation: number;
  /** Impulsivity level (0-100, higher = more impulsive) */
  readonly impulsivity: number;
  /** Verification tendency (0-100, higher = more cautious — POSITIVE axis) */
  readonly verification: number;
  /** Self-awareness level (0-100, higher = more aware — POSITIVE axis) */
  readonly awareness: number;
  /**
   * Weighted risk score computed from the 4 dimensions.
   * Formula: activation*0.35 + impulsivity*0.30 + (100-verification)*0.20 + (100-awareness)*0.15
   */
  readonly riskScore: number;
}

// ---------------------------------------------------------------------------
// Training targets — what the session focuses on
// ---------------------------------------------------------------------------

/** Cognitive lever the training session targets */
export type TrainingTarget =
  | 'urgency'        // resist time pressure
  | 'responsibility' // resist duty/guilt manipulation
  | 'fear'           // resist fear-based control
  | 'trust'          // resist rapid trust building
  | 'easy_gain'      // resist too-good-to-be-true offers
  | 'authority';     // resist fake authority figures

/** Gender presentation of the scammer in the training scenario */
export type ScammerGender = 'male' | 'female' | 'unspecified';

// ---------------------------------------------------------------------------
// Session phase — state machine
// ---------------------------------------------------------------------------

/** Current phase of a training session */
export type SessionPhase =
  | 'setup'          // choosing scenario parameters
  | 'conversation'   // active AI chat
  | 'interrupted'    // risk threshold hit, transitioning to reflection
  | 'reflection'     // R1-R4 guided questions
  | 'replay'         // short replay of the trigger moment (V2)
  | 'summary'        // final report displayed
  | 'complete';      // done, saved

// ---------------------------------------------------------------------------
// Narrative phases — conversation progression
// ---------------------------------------------------------------------------

/** Narrative phase within the AI conversation */
export type NarrativePhase =
  | 'P1'  // normalità — plausible opening contact
  | 'P2'  // attivazione invisibile — escalating involvement
  | 'P3'; // micro-spinta — observing acceleration

// ---------------------------------------------------------------------------
// Reflection
// ---------------------------------------------------------------------------

/** Reflection step identifier */
export type ReflectionStep = 'R1' | 'R2' | 'R3' | 'R4';

/** A user's answer to one reflection question + AI analysis */
export interface ReflectionAnswer {
  readonly step: ReflectionStep;
  readonly question: string;
  readonly userAnswer: string;
  readonly aiAnalysis: string;
}

// ---------------------------------------------------------------------------
// Scenario configuration — sent to Worker with every request
// ---------------------------------------------------------------------------

/** Scammer persona generated by AI at session start */
export interface ScammerPersona {
  readonly name: string;
  readonly role: string;
  readonly tone: string;
}

/** Reason why the training session was interrupted */
export type InterruptReason = 'high_risk' | 'max_turns';

/** Scenario parameters for a training session */
export interface ScenarioConfig {
  readonly scenarioId: string;
  readonly attackType: AttackType;
  readonly difficulty: 'easy' | 'medium' | 'hard';
  /** @deprecated Use trainingTargets instead. Kept for backward compatibility. */
  readonly trainingTarget: TrainingTarget;
  readonly trainingTargets: TrainingTarget[];
  readonly scammerGender?: ScammerGender;
  readonly scammerPersona: ScammerPersona;
  /** Risk score threshold for interruption (0-100, default 70) */
  readonly interruptThreshold: number;
  /** Minimum turns before interruption can trigger (default 3) */
  readonly minTurnsBeforeInterrupt: number;
  /** Maximum user turns before forced interruption */
  readonly maxTurns: number;
}

// ---------------------------------------------------------------------------
// Conversation turn — a single message in the chat
// ---------------------------------------------------------------------------

/** Who sent the message in a training conversation */
export type TrainingRole = 'user' | 'scammer' | 'system';

/** A single message in the training conversation */
export interface ConversationTurn {
  readonly id: string;
  readonly timestamp: string;
  readonly role: TrainingRole;
  readonly content: string;
  /** Behavior scores — only present on user turns (computed by Gemini) */
  readonly scores?: BehaviorScores;
  /** Narrative phase when this turn occurred */
  readonly phase: NarrativePhase;
}

// ---------------------------------------------------------------------------
// Training session — full session state
// ---------------------------------------------------------------------------

/** Complete state of a training session */
export interface TrainingSession {
  readonly sessionId: string;
  readonly createdAt: string;
  readonly scenarioConfig: ScenarioConfig;
  readonly phase: SessionPhase;
  readonly turns: ConversationTurn[];
  readonly reflections: ReflectionAnswer[];
  readonly finalScores: BehaviorScores | null;
  /** Turn index where the system interrupted (null if not yet interrupted) */
  readonly interruptedAtTurn: number | null;
  /** The user message that triggered interruption (for reflection context) */
  readonly triggerMessage: string | null;
}

// ---------------------------------------------------------------------------
// User profile — persists across sessions (V2, encrypted localStorage)
// ---------------------------------------------------------------------------

/** A recurring behavioral pattern detected across sessions */
export interface UserPattern {
  readonly patternId: string;
  readonly dimension: TrainingDimension;
  readonly description: string;
  /** How many sessions this pattern has been observed in */
  readonly frequency: number;
  readonly firstSeen: string;
  readonly lastSeen: string;
}

/** Summary of a completed session (lightweight, for history) */
export interface SessionSummary {
  readonly sessionId: string;
  readonly date: string;
  readonly attackType: AttackType;
  readonly trainingTarget: TrainingTarget;
  readonly finalRiskScore: number;
  readonly interruptedAtTurn: number | null;
  /** Delta improvement compared to previous session on same dimension */
  readonly improvement: number;
}

/** Cross-session vulnerability profile */
export interface UserProfile {
  readonly sessionsCompleted: number;
  readonly averageScores: Record<TrainingDimension, number>;
  readonly weakestDimension: TrainingDimension | null;
  readonly patterns: readonly UserPattern[];
  /** Last 20 session summaries, newest first */
  readonly sessionHistory: readonly SessionSummary[];
}

// ---------------------------------------------------------------------------
// Custom scenarios — user-created training scenarios
// ---------------------------------------------------------------------------

/** A user-created custom training scenario */
export interface CustomScenario {
  readonly id: string;
  readonly name: string;
  /** Short description for display */
  readonly description: string;
  /** Detailed attack description sent to Gemini */
  readonly attackDescription: string;
  readonly scammerPersona: ScammerPersona;
  readonly trainingTarget: TrainingTarget;
  readonly difficulty: 'easy' | 'medium' | 'hard';
  readonly createdAt: string;
}

// ---------------------------------------------------------------------------
// Worker API types — request/response for /api/training/* endpoints
// ---------------------------------------------------------------------------

/** POST /api/training/start — request body */
export interface StartSessionRequest {
  readonly attackType: AttackType;
  readonly difficulty: 'easy' | 'medium' | 'hard';
  readonly trainingTargets: TrainingTarget[];
  readonly scammerGender?: ScammerGender;
  /** Custom scenario description — when present, overrides attackType for prompt generation */
  readonly customDescription?: string;
  /** Custom scammer persona — when present, used instead of AI-generated one */
  readonly customPersona?: ScammerPersona;
}

/** POST /api/training/start — response body */
export interface StartSessionResponse {
  readonly scenarioConfig: ScenarioConfig;
  readonly firstMessage: string;
}

/** POST /api/training/message — request body */
export interface SendMessageRequest {
  readonly scenarioConfig: ScenarioConfig;
  readonly conversationHistory: readonly ConversationTurn[];
  readonly userMessage: string;
  readonly turnCount: number;
}

/** POST /api/training/message — response body */
export interface SendMessageResponse {
  readonly aiMessage: string;
  readonly behaviorScores: BehaviorScores;
  readonly shouldInterrupt: boolean;
  readonly interruptReason?: InterruptReason;
  readonly nextPhase: NarrativePhase;
}

/** POST /api/training/reflect — request body */
export interface ReflectionRequest {
  readonly scenarioConfig: ScenarioConfig;
  readonly triggerMessage: string;
  readonly reflectionStep: ReflectionStep;
  readonly userAnswer: string;
  readonly previousReflections: readonly ReflectionAnswer[];
}

/** POST /api/training/reflect — response body */
export interface ReflectionResponse {
  readonly aiAnalysis: string;
  /** Next question text, or null if reflection is complete */
  readonly nextQuestion: string | null;
  /** Summary provided after the last reflection step */
  readonly insightSummary?: string;
}
