/**
 * Zod schemas for runtime validation of Gemini-generated Simulation objects.
 *
 * Mirrors cyberpedia-antiscam-tool/src/types/simulation.ts exactly.
 * Keep in sync manually — if frontend types change, update this file.
 *
 * Design decisions:
 * - .strict() only on top-level SimulationSchema and ChoiceOptionSchema (leaf with no extra fields expected)
 * - Step sub-schemas (SimMessage, SimChoice, SimFeedback) use strip mode (Zod default) so that
 *   extra fields generated by the LLM on flat-schema responses are silently discarded
 * - .readonly() where applicable: reflects the frontend's readonly interfaces
 * - SimStepSchema uses z.discriminatedUnion('type') for type-safe narrowing
 * - SimFeedback has NO 'correct' field (removed in R2 refactor)
 *
 * Exported schemas (for validation + debug):
 *   SimulationSchema    — top-level, use for full response validation
 *   SimStepSchema       — individual step validation during debug
 *   SimFeedbackSchema   — feedback step validation during debug
 */

import { z } from 'zod';

// ── Sender ────────────────────────────────────────────────────────────────────

const SenderSchema = z.enum(['scammer', 'user', 'system']);

// ── SimMessage ────────────────────────────────────────────────────────────────
// mirrors: { readonly type: 'message'; readonly sender: Sender;
//            readonly text: string; readonly delay?: number }

export const SimMessageSchema = z
  .object({
    type: z.literal('message'),
    sender: SenderSchema,
    text: z.string().min(1),
    delay: z.number().int().positive().optional(),
  })
  .readonly();

// ── ChoiceOption ──────────────────────────────────────────────────────────────
// mirrors: { readonly id: string; readonly text: string; readonly correct: boolean;
//            readonly skill?: ChoiceSkill }
// Not exported — only used inside SimChoiceSchema

const ChoiceSkillSchema = z.enum(['limite', 'verifica', 'esposizione', 'alternativa']);

const ChoiceOptionSchema = z
  .object({
    id: z.string().min(1),
    text: z.string().min(1),
    correct: z.boolean(),
    skill: ChoiceSkillSchema.optional(),
  })
  .strict()
  .readonly();

// ── SimChoice ─────────────────────────────────────────────────────────────────
// mirrors: { readonly type: 'choice'; readonly options: readonly ChoiceOption[] }
//
// I2 rule enforced here: exactly 2 options must be correct:true, each ideally
// training a different skill (limite / verifica / esposizione / alternativa).
// The skills are not validated for uniqueness here (too strict for LLM output),
// but the count of 2 is a hard gate.

export const SimChoiceSchema = z
  .object({
    type: z.literal('choice'),
    options: z.array(ChoiceOptionSchema).min(2).max(4).readonly(),
  })
  .refine(
    (data) => data.options.filter((o) => o.correct).length === 2,
    { message: 'I2: ogni SimChoice deve avere esattamente 2 opzioni correct:true' },
  )
  .readonly();

// ── SimFeedback ───────────────────────────────────────────────────────────────
// mirrors: { readonly type: 'feedback'; readonly explanation: string;
//            readonly wrongExplanation?: string; readonly retryMessage?: SimMessage;
//            readonly followUp: readonly SimMessage[] }
// NOTE: no 'correct' field — removed in R2 (was present in original SimFeedback)

export const SimFeedbackSchema = z
  .object({
    type: z.literal('feedback'),
    explanation: z.string().min(1),
    wrongExplanation: z.string().optional(),
    retryMessage: SimMessageSchema.optional(),
    followUp: z.array(SimMessageSchema).readonly(),
  })
  .readonly();

// ── SimStep (discriminated union) ─────────────────────────────────────────────
// mirrors: SimMessage | SimChoice | SimFeedback
// Discriminator: 'type' field — 'message' | 'choice' | 'feedback'

export const SimStepSchema = z.discriminatedUnion('type', [
  SimMessageSchema,
  SimChoiceSchema,
  SimFeedbackSchema,
]);

// ── Simulation ────────────────────────────────────────────────────────────────
// mirrors: { readonly id: string; readonly title: string; readonly description: string;
//            readonly icon: string; readonly scammerName: string;
//            readonly steps: readonly SimStep[] }

export const SimulationSchema = z
  .object({
    id: z.string().min(1),
    title: z.string().min(1),
    description: z.string().min(1),
    icon: z.enum(['Heart', 'Wallet', 'Building2', 'Users']),
    scammerName: z.string().min(1),
    steps: z.array(SimStepSchema).min(1).readonly(),
  })
  .strict()
  .readonly();

// ── Inferred output type ──────────────────────────────────────────────────────
// Use this for the return type of the Worker's generate handler (Phase 2)

export type SimulationOutput = z.output<typeof SimulationSchema>;
